# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/mem_1/mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem || ORIG_REF_NAME==mem} -quiet] -quiet
