webtalk_init -webtalk_dir C:/Xilinx/Vivado2020.1/Vivado/2020.1/examples/2020_VSP/Lab03/all/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/TM_M8x8_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  7 14:00:53 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bb702601-d366-44b6-8c65-df5540b8826c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d889b0aefaba4a7ea910994bb70f34a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2895 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1258582915 -regid "" -xml C:/Xilinx/Vivado2020.1/Vivado/2020.1/examples/2020_VSP/Lab03/all/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/TM_M8x8_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Xilinx/Vivado2020.1/Vivado/2020.1/examples/2020_VSP/Lab03/all/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/TM_M8x8_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Xilinx/Vivado2020.1/Vivado/2020.1/examples/2020_VSP/Lab03/all/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/TM_M8x8_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
